//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Service.RC.FactElect {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_ComprobanteElectronico", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_ComprobanteElectronico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_ComprobanteDetalle[] ComprobanteDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_DescuentoCargo[] DescuentoCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_DocumentoReferencia[] DocumentoReferenciaDespachoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_DocumentoReferenciaNota[] DocumentoReferenciaNotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_DocumentoSustentoNota DocumentoSustentoNotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_Emisor EmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaEmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaVencimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraEmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImporteTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_Leyenda[] LeyendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_MontosTotales MontoTotalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_Receptor ReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoDetraccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoOperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalDescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalImpuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPrecioVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalValorVentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_ComprobanteDetalle[] ComprobanteDetalle {
            get {
                return this.ComprobanteDetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.ComprobanteDetalleField, value) != true)) {
                    this.ComprobanteDetalleField = value;
                    this.RaisePropertyChanged("ComprobanteDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_DescuentoCargo[] DescuentoCargo {
            get {
                return this.DescuentoCargoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescuentoCargoField, value) != true)) {
                    this.DescuentoCargoField = value;
                    this.RaisePropertyChanged("DescuentoCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_DocumentoReferencia[] DocumentoReferenciaDespacho {
            get {
                return this.DocumentoReferenciaDespachoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoReferenciaDespachoField, value) != true)) {
                    this.DocumentoReferenciaDespachoField = value;
                    this.RaisePropertyChanged("DocumentoReferenciaDespacho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_DocumentoReferenciaNota[] DocumentoReferenciaNota {
            get {
                return this.DocumentoReferenciaNotaField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoReferenciaNotaField, value) != true)) {
                    this.DocumentoReferenciaNotaField = value;
                    this.RaisePropertyChanged("DocumentoReferenciaNota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_DocumentoSustentoNota DocumentoSustentoNota {
            get {
                return this.DocumentoSustentoNotaField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoSustentoNotaField, value) != true)) {
                    this.DocumentoSustentoNotaField = value;
                    this.RaisePropertyChanged("DocumentoSustentoNota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_Emisor Emisor {
            get {
                return this.EmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.EmisorField, value) != true)) {
                    this.EmisorField = value;
                    this.RaisePropertyChanged("Emisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaEmision {
            get {
                return this.FechaEmisionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaEmisionField, value) != true)) {
                    this.FechaEmisionField = value;
                    this.RaisePropertyChanged("FechaEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaVencimiento {
            get {
                return this.FechaVencimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaVencimientoField, value) != true)) {
                    this.FechaVencimientoField = value;
                    this.RaisePropertyChanged("FechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraEmision {
            get {
                return this.HoraEmisionField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraEmisionField, value) != true)) {
                    this.HoraEmisionField = value;
                    this.RaisePropertyChanged("HoraEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ImporteTotal {
            get {
                return this.ImporteTotalField;
            }
            set {
                if ((this.ImporteTotalField.Equals(value) != true)) {
                    this.ImporteTotalField = value;
                    this.RaisePropertyChanged("ImporteTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_Leyenda[] Leyenda {
            get {
                return this.LeyendaField;
            }
            set {
                if ((object.ReferenceEquals(this.LeyendaField, value) != true)) {
                    this.LeyendaField = value;
                    this.RaisePropertyChanged("Leyenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_MontosTotales MontoTotales {
            get {
                return this.MontoTotalesField;
            }
            set {
                if ((object.ReferenceEquals(this.MontoTotalesField, value) != true)) {
                    this.MontoTotalesField = value;
                    this.RaisePropertyChanged("MontoTotales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_Receptor Receptor {
            get {
                return this.ReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceptorField, value) != true)) {
                    this.ReceptorField = value;
                    this.RaisePropertyChanged("Receptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieNumero {
            get {
                return this.SerieNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieNumeroField, value) != true)) {
                    this.SerieNumeroField = value;
                    this.RaisePropertyChanged("SerieNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoDetraccion {
            get {
                return this.TextoDetraccionField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoDetraccionField, value) != true)) {
                    this.TextoDetraccionField = value;
                    this.RaisePropertyChanged("TextoDetraccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoComprobante {
            get {
                return this.TipoComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoComprobanteField, value) != true)) {
                    this.TipoComprobanteField = value;
                    this.RaisePropertyChanged("TipoComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoOperacion {
            get {
                return this.TipoOperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoOperacionField, value) != true)) {
                    this.TipoOperacionField = value;
                    this.RaisePropertyChanged("TipoOperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalCargo {
            get {
                return this.TotalCargoField;
            }
            set {
                if ((this.TotalCargoField.Equals(value) != true)) {
                    this.TotalCargoField = value;
                    this.RaisePropertyChanged("TotalCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalDescuento {
            get {
                return this.TotalDescuentoField;
            }
            set {
                if ((this.TotalDescuentoField.Equals(value) != true)) {
                    this.TotalDescuentoField = value;
                    this.RaisePropertyChanged("TotalDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalImpuesto {
            get {
                return this.TotalImpuestoField;
            }
            set {
                if ((this.TotalImpuestoField.Equals(value) != true)) {
                    this.TotalImpuestoField = value;
                    this.RaisePropertyChanged("TotalImpuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPrecioVenta {
            get {
                return this.TotalPrecioVentaField;
            }
            set {
                if ((this.TotalPrecioVentaField.Equals(value) != true)) {
                    this.TotalPrecioVentaField = value;
                    this.RaisePropertyChanged("TotalPrecioVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalValorVenta {
            get {
                return this.TotalValorVentaField;
            }
            set {
                if ((this.TotalValorVentaField.Equals(value) != true)) {
                    this.TotalValorVentaField = value;
                    this.RaisePropertyChanged("TotalValorVenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_DocumentoSustentoNota", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_DocumentoSustentoNota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoMotivoAnulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoAnulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieNumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoMotivoAnulacion {
            get {
                return this.CodigoMotivoAnulacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoMotivoAnulacionField, value) != true)) {
                    this.CodigoMotivoAnulacionField = value;
                    this.RaisePropertyChanged("CodigoMotivoAnulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoAnulacion {
            get {
                return this.MotivoAnulacionField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoAnulacionField, value) != true)) {
                    this.MotivoAnulacionField = value;
                    this.RaisePropertyChanged("MotivoAnulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieNumero {
            get {
                return this.SerieNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieNumeroField, value) != true)) {
                    this.SerieNumeroField = value;
                    this.RaisePropertyChanged("SerieNumero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_Emisor", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_Emisor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoDomicilioFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_Contacto ContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoIdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaginaWebField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoIdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrbanizacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDomicilioFiscal {
            get {
                return this.CodigoDomicilioFiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoDomicilioFiscalField, value) != true)) {
                    this.CodigoDomicilioFiscalField = value;
                    this.RaisePropertyChanged("CodigoDomicilioFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPais {
            get {
                return this.CodigoPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPaisField, value) != true)) {
                    this.CodigoPaisField = value;
                    this.RaisePropertyChanged("CodigoPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUbigeo {
            get {
                return this.CodigoUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoUbigeoField, value) != true)) {
                    this.CodigoUbigeoField = value;
                    this.RaisePropertyChanged("CodigoUbigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_Contacto Contacto {
            get {
                return this.ContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactoField, value) != true)) {
                    this.ContactoField = value;
                    this.RaisePropertyChanged("Contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercial {
            get {
                return this.NombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComercialField, value) != true)) {
                    this.NombreComercialField = value;
                    this.RaisePropertyChanged("NombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumentoIdentidad {
            get {
                return this.NumeroDocumentoIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoIdentidadField, value) != true)) {
                    this.NumeroDocumentoIdentidadField = value;
                    this.RaisePropertyChanged("NumeroDocumentoIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaginaWeb {
            get {
                return this.PaginaWebField;
            }
            set {
                if ((object.ReferenceEquals(this.PaginaWebField, value) != true)) {
                    this.PaginaWebField = value;
                    this.RaisePropertyChanged("PaginaWeb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoIdentidad {
            get {
                return this.TipoDocumentoIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoIdentidadField, value) != true)) {
                    this.TipoDocumentoIdentidadField = value;
                    this.RaisePropertyChanged("TipoDocumentoIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Urbanizacion {
            get {
                return this.UrbanizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UrbanizacionField, value) != true)) {
                    this.UrbanizacionField = value;
                    this.RaisePropertyChanged("Urbanizacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_MontosTotales", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_MontosTotales : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_Gravado GravadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_Gravado Gravado {
            get {
                return this.GravadoField;
            }
            set {
                if ((object.ReferenceEquals(this.GravadoField, value) != true)) {
                    this.GravadoField = value;
                    this.RaisePropertyChanged("Gravado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_Receptor", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_Receptor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoDomicilioFiscalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_Contacto ContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoIdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaginaWebField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoIdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrbanizacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDomicilioFiscal {
            get {
                return this.CodigoDomicilioFiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoDomicilioFiscalField, value) != true)) {
                    this.CodigoDomicilioFiscalField = value;
                    this.RaisePropertyChanged("CodigoDomicilioFiscal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPais {
            get {
                return this.CodigoPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPaisField, value) != true)) {
                    this.CodigoPaisField = value;
                    this.RaisePropertyChanged("CodigoPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUbigeo {
            get {
                return this.CodigoUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoUbigeoField, value) != true)) {
                    this.CodigoUbigeoField = value;
                    this.RaisePropertyChanged("CodigoUbigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_Contacto Contacto {
            get {
                return this.ContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactoField, value) != true)) {
                    this.ContactoField = value;
                    this.RaisePropertyChanged("Contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercial {
            get {
                return this.NombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComercialField, value) != true)) {
                    this.NombreComercialField = value;
                    this.RaisePropertyChanged("NombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumentoIdentidad {
            get {
                return this.NumeroDocumentoIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoIdentidadField, value) != true)) {
                    this.NumeroDocumentoIdentidadField = value;
                    this.RaisePropertyChanged("NumeroDocumentoIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaginaWeb {
            get {
                return this.PaginaWebField;
            }
            set {
                if ((object.ReferenceEquals(this.PaginaWebField, value) != true)) {
                    this.PaginaWebField = value;
                    this.RaisePropertyChanged("PaginaWeb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumentoIdentidad {
            get {
                return this.TipoDocumentoIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoIdentidadField, value) != true)) {
                    this.TipoDocumentoIdentidadField = value;
                    this.RaisePropertyChanged("TipoDocumentoIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Urbanizacion {
            get {
                return this.UrbanizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UrbanizacionField, value) != true)) {
                    this.UrbanizacionField = value;
                    this.RaisePropertyChanged("Urbanizacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_ComprobanteDetalle", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_ComprobanteDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoSunatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTipoPrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_ComprobanteDetalleImpuestos[] ComprobanteDetalleImpuestosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImpuestoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] MultiDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadMedidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorVentaUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorVentaUnitarioIncIgvField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSunat {
            get {
                return this.CodigoSunatField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoSunatField, value) != true)) {
                    this.CodigoSunatField = value;
                    this.RaisePropertyChanged("CodigoSunat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTipoPrecio {
            get {
                return this.CodigoTipoPrecioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTipoPrecioField, value) != true)) {
                    this.CodigoTipoPrecioField = value;
                    this.RaisePropertyChanged("CodigoTipoPrecio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_ComprobanteDetalleImpuestos[] ComprobanteDetalleImpuestos {
            get {
                return this.ComprobanteDetalleImpuestosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComprobanteDetalleImpuestosField, value) != true)) {
                    this.ComprobanteDetalleImpuestosField = value;
                    this.RaisePropertyChanged("ComprobanteDetalleImpuestos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ImpuestoTotal {
            get {
                return this.ImpuestoTotalField;
            }
            set {
                if ((this.ImpuestoTotalField.Equals(value) != true)) {
                    this.ImpuestoTotalField = value;
                    this.RaisePropertyChanged("ImpuestoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Item {
            get {
                return this.ItemField;
            }
            set {
                if ((this.ItemField.Equals(value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] MultiDescripcion {
            get {
                return this.MultiDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.MultiDescripcionField, value) != true)) {
                    this.MultiDescripcionField = value;
                    this.RaisePropertyChanged("MultiDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadMedida {
            get {
                return this.UnidadMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadMedidaField, value) != true)) {
                    this.UnidadMedidaField = value;
                    this.RaisePropertyChanged("UnidadMedida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorVentaUnitario {
            get {
                return this.ValorVentaUnitarioField;
            }
            set {
                if ((this.ValorVentaUnitarioField.Equals(value) != true)) {
                    this.ValorVentaUnitarioField = value;
                    this.RaisePropertyChanged("ValorVentaUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorVentaUnitarioIncIgv {
            get {
                return this.ValorVentaUnitarioIncIgvField;
            }
            set {
                if ((this.ValorVentaUnitarioIncIgvField.Equals(value) != true)) {
                    this.ValorVentaUnitarioIncIgvField = value;
                    this.RaisePropertyChanged("ValorVentaUnitarioIncIgv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_DescuentoCargo", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_DescuentoCargo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoMotivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FactorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IndicadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoMotivo {
            get {
                return this.CodigoMotivoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoMotivoField, value) != true)) {
                    this.CodigoMotivoField = value;
                    this.RaisePropertyChanged("CodigoMotivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Factor {
            get {
                return this.FactorField;
            }
            set {
                if ((this.FactorField.Equals(value) != true)) {
                    this.FactorField = value;
                    this.RaisePropertyChanged("Factor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Indicador {
            get {
                return this.IndicadorField;
            }
            set {
                if ((this.IndicadorField.Equals(value) != true)) {
                    this.IndicadorField = value;
                    this.RaisePropertyChanged("Indicador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoBase {
            get {
                return this.MontoBaseField;
            }
            set {
                if ((this.MontoBaseField.Equals(value) != true)) {
                    this.MontoBaseField = value;
                    this.RaisePropertyChanged("MontoBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoTotal {
            get {
                return this.MontoTotalField;
            }
            set {
                if ((this.MontoTotalField.Equals(value) != true)) {
                    this.MontoTotalField = value;
                    this.RaisePropertyChanged("MontoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivo {
            get {
                return this.MotivoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoField, value) != true)) {
                    this.MotivoField = value;
                    this.RaisePropertyChanged("Motivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_DocumentoReferencia", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_DocumentoReferencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieNumero {
            get {
                return this.SerieNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieNumeroField, value) != true)) {
                    this.SerieNumeroField = value;
                    this.RaisePropertyChanged("SerieNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_DocumentoReferenciaNota", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_DocumentoReferenciaNota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieNumero {
            get {
                return this.SerieNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieNumeroField, value) != true)) {
                    this.SerieNumeroField = value;
                    this.RaisePropertyChanged("SerieNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_Leyenda", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_Leyenda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_ComprobanteDetalleImpuestos", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_ComprobanteDetalleImpuestos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AfectacionIGVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoInternacionalTributoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTributoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoTotalImpuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreTributoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PorcentajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AfectacionIGV {
            get {
                return this.AfectacionIGVField;
            }
            set {
                if ((object.ReferenceEquals(this.AfectacionIGVField, value) != true)) {
                    this.AfectacionIGVField = value;
                    this.RaisePropertyChanged("AfectacionIGV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoInternacionalTributo {
            get {
                return this.CodigoInternacionalTributoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoInternacionalTributoField, value) != true)) {
                    this.CodigoInternacionalTributoField = value;
                    this.RaisePropertyChanged("CodigoInternacionalTributo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTributo {
            get {
                return this.CodigoTributoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTributoField, value) != true)) {
                    this.CodigoTributoField = value;
                    this.RaisePropertyChanged("CodigoTributo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoBase {
            get {
                return this.MontoBaseField;
            }
            set {
                if ((this.MontoBaseField.Equals(value) != true)) {
                    this.MontoBaseField = value;
                    this.RaisePropertyChanged("MontoBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoTotalImpuesto {
            get {
                return this.MontoTotalImpuestoField;
            }
            set {
                if ((this.MontoTotalImpuestoField.Equals(value) != true)) {
                    this.MontoTotalImpuestoField = value;
                    this.RaisePropertyChanged("MontoTotalImpuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTributo {
            get {
                return this.NombreTributoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreTributoField, value) != true)) {
                    this.NombreTributoField = value;
                    this.RaisePropertyChanged("NombreTributo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Porcentaje {
            get {
                return this.PorcentajeField;
            }
            set {
                if ((this.PorcentajeField.Equals(value) != true)) {
                    this.PorcentajeField = value;
                    this.RaisePropertyChanged("Porcentaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_Contacto", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_Contacto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_Gravado", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_Gravado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Web.Service.RC.FactElect.En_GrabadoIGV GravadoIGVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Web.Service.RC.FactElect.En_GrabadoIGV GravadoIGV {
            get {
                return this.GravadoIGVField;
            }
            set {
                if ((object.ReferenceEquals(this.GravadoIGVField, value) != true)) {
                    this.GravadoIGVField = value;
                    this.RaisePropertyChanged("GravadoIGV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_GrabadoIGV", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_GrabadoIGV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoTotalImpuestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PorcentajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoBase {
            get {
                return this.MontoBaseField;
            }
            set {
                if ((this.MontoBaseField.Equals(value) != true)) {
                    this.MontoBaseField = value;
                    this.RaisePropertyChanged("MontoBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoTotalImpuesto {
            get {
                return this.MontoTotalImpuestoField;
            }
            set {
                if ((this.MontoTotalImpuestoField.Equals(value) != true)) {
                    this.MontoTotalImpuestoField = value;
                    this.RaisePropertyChanged("MontoTotalImpuesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Porcentaje {
            get {
                return this.PorcentajeField;
            }
            set {
                if ((this.PorcentajeField.Equals(value) != true)) {
                    this.PorcentajeField = value;
                    this.RaisePropertyChanged("Porcentaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="En_Respuesta", Namespace="http://schemas.datacontract.org/2004/07/FactElec.CapaEntidad.RegistroComprobante")]
    [System.SerializableAttribute()]
    public partial class En_Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.RC.FactElect.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistroComprobante", ReplyAction="http://tempuri.org/IService1/RegistroComprobanteResponse")]
        Web.Service.RC.FactElect.En_Respuesta RegistroComprobante(Web.Service.RC.FactElect.En_ComprobanteElectronico Comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistroComprobante", ReplyAction="http://tempuri.org/IService1/RegistroComprobanteResponse")]
        System.Threading.Tasks.Task<Web.Service.RC.FactElect.En_Respuesta> RegistroComprobanteAsync(Web.Service.RC.FactElect.En_ComprobanteElectronico Comprobante);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Web.Service.RC.FactElect.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Web.Service.RC.FactElect.IService1>, Web.Service.RC.FactElect.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Web.Service.RC.FactElect.En_Respuesta RegistroComprobante(Web.Service.RC.FactElect.En_ComprobanteElectronico Comprobante) {
            return base.Channel.RegistroComprobante(Comprobante);
        }
        
        public System.Threading.Tasks.Task<Web.Service.RC.FactElect.En_Respuesta> RegistroComprobanteAsync(Web.Service.RC.FactElect.En_ComprobanteElectronico Comprobante) {
            return base.Channel.RegistroComprobanteAsync(Comprobante);
        }
    }
}
