//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        public int idCaja { get; set; }
        public string idUsuario { get; set; }
        public Nullable<decimal> ingresos { get; set; }
        public Nullable<decimal> saldonIcial { get; set; }
        public Nullable<decimal> saldoFinal { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
        public string usuarioRegistro { get; set; }
        public string usuarioActualizacion { get; set; }
        public string estado { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
