//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_ComprobanteDetalle
    {
        public int idDetalleComprobante { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idComprobante { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> montoUnitario { get; set; }
    
        public virtual CO_Comprobante CO_Comprobante { get; set; }
        public virtual WH_ProductoServicio WH_ProductoServicio { get; set; }
    }
}
