//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compania
    {
        public int idCompania { get; set; }
        public string razonSocial { get; set; }
        public string ruc { get; set; }
        public string domicilioFiscal { get; set; }
        public string correo { get; set; }
        public Nullable<int> idTitular { get; set; }
        public Nullable<int> idContacto { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
        public string usuarioRegistro { get; set; }
        public string usuarioActualizacion { get; set; }
    
        public virtual PersonaMast PersonaMast { get; set; }
        public virtual PersonaMast PersonaMast1 { get; set; }
    }
}
