//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrelativoMast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CorrelativoMast()
        {
            this.CO_Comprobante = new HashSet<CO_Comprobante>();
        }
    
        public int idCorrelativo { get; set; }
        public Nullable<int> idTipoComprobante { get; set; }
        public string serie { get; set; }
        public string correlativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_Comprobante> CO_Comprobante { get; set; }
        public virtual CO_TipoComprobante CO_TipoComprobante { get; set; }
    }
}
