//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_InventarioDetalle
    {
        public int idDetalleInventario { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<int> stockAntes { get; set; }
        public Nullable<int> stockDespues { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> idInventario { get; set; }
        public string idUsuario { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual WH_Inventario WH_Inventario { get; set; }
        public virtual WH_ProductoServicio WH_ProductoServicio { get; set; }
    }
}
