//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_ProductoServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WH_ProductoServicio()
        {
            this.CO_ComprobanteDetalle = new HashSet<CO_ComprobanteDetalle>();
            this.WH_InventarioDetalle = new HashSet<WH_InventarioDetalle>();
        }
    
        public int idProducto { get; set; }
        public Nullable<int> idTipoProductoServicio { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> stock { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
        public string usuarioRegistro { get; set; }
        public string usuarioActualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_ComprobanteDetalle> CO_ComprobanteDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WH_InventarioDetalle> WH_InventarioDetalle { get; set; }
        public virtual WH_TipoProductoServicio WH_TipoProductoServicio { get; set; }
    }
}
